version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/portfolio:latest
    ports:
      - "4173:4173"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app
    restart: unless-stopped